import { desc, sql } from "drizzle-orm";
import { check, foreignKey, index, integer, sqliteTable, text, unique, uniqueIndex } from "drizzle-orm/sqlite-core";

export const researchRunsTable = sqliteTable(
  "research_runs",
  {
    id: text("id").notNull().primaryKey(),
    requestKey: text("request_key").notNull().unique(),
    status: text("status", { enum: ["pending", "running", "finalizing", "recovering", "completed", "partial", "cancelled", "failed", "corrupt"] }).notNull(),
    mode: text("mode", { enum: ["live", "fixture"] }).notNull(),
    fixtureId: text("fixture_id"),
    requestJson: text("request_json").notNull(),
    requestDigest: text("request_digest").notNull(),
    orchestratorDigest: text("orchestrator_digest").notNull(),
    evidenceSetDigest: text("evidence_set_digest"),
    resultJson: text("result_json"),
    resultDigest: text("result_digest"),
    usable: integer("usable").notNull().default(0),
    stopReason: text("stop_reason", { enum: ["partial_sources", "user_cancelled", "no_usable_result", "orchestration_failed", "persisted_data_corrupt"] }),
    cancelRequestedAt: integer("cancel_requested_at"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    completedAt: integer("completed_at"),
  },
  (table) => [
    check("ck_research_runs_status", sql`${table.status} IN ('pending','running','finalizing','recovering','completed','partial','cancelled','failed','corrupt')`),
    check("ck_research_runs_mode", sql`${table.mode} IN ('live','fixture')`),
    check("ck_research_runs_usable", sql`${table.usable} IN (0,1)`),
    check("ck_research_runs_stop_reason", sql`${table.stopReason} IN ('partial_sources','user_cancelled','no_usable_result','orchestration_failed','persisted_data_corrupt')`),
    check("ck_research_runs_fixture", sql`(${table.mode}='fixture') = (${table.fixtureId} IS NOT NULL)`),
    check("ck_research_runs_result_json", sql`(${table.status} IN ('completed','partial')) = (${table.resultJson} IS NOT NULL)`),
    check("ck_research_runs_result_digest", sql`(${table.status} IN ('completed','partial')) = (${table.resultDigest} IS NOT NULL)`),
    check("ck_research_runs_evidence_digest", sql`(${table.status} IN ('completed','partial')) = (${table.evidenceSetDigest} IS NOT NULL)`),
    check("ck_research_runs_usable_state", sql`(${table.status} IN ('completed','partial')) = (${table.usable}=1)`),
    index("idx_research_runs_prompt").on(table.usable, desc(table.completedAt)),
  ],
);

export const researchSourcesTable = sqliteTable(
  "research_sources",
  {
    id: text("id").notNull().primaryKey(),
    runId: text("run_id").notNull().references(() => researchRunsTable.id, { onDelete: "cascade" }),
    ordinal: integer("ordinal").notNull(),
    kind: text("kind", { enum: ["web", "repository", "document", "fixture"] }).notNull(),
    locator: text("locator").notNull(),
    canonicalLocator: text("canonical_locator").notNull(),
    dedupKey: text("dedup_key").notNull(),
    duplicateOfSourceId: text("duplicate_of_source_id"),
    status: text("status", { enum: ["pending", "running", "recovering", "succeeded", "failed", "duplicate", "cancelled", "corrupt"] }).notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    httpStatus: integer("http_status"),
    contentDigest: text("content_digest"),
    evidenceJson: text("evidence_json"),
    findingJson: text("finding_json"),
    findingDigest: text("finding_digest"),
    errorCode: text("error_code", { enum: ["source_timeout", "fetch_failed", "malformed_source", "worker_failed", "invalid_worker_output", "user_cancelled", "persisted_data_corrupt"] }),
    errorMessage: text("error_message"),
    startedAt: integer("started_at"),
    finishedAt: integer("finished_at"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    foreignKey({ columns: [table.duplicateOfSourceId], foreignColumns: [table.id] }).onDelete("restrict"),
    unique().on(table.runId, table.ordinal),
    check("ck_research_sources_kind", sql`${table.kind} IN ('web','repository','document','fixture')`),
    check("ck_research_sources_status", sql`${table.status} IN ('pending','running','recovering','succeeded','failed','duplicate','cancelled','corrupt')`),
    check("ck_research_sources_error_code", sql`${table.errorCode} IN ('source_timeout','fetch_failed','malformed_source','worker_failed','invalid_worker_output','user_cancelled','persisted_data_corrupt')`),
    check("ck_research_sources_duplicate", sql`(${table.status}='duplicate') = (${table.duplicateOfSourceId} IS NOT NULL)`),
    check("ck_research_sources_success", sql`${table.status}!='succeeded' OR (${table.contentDigest} IS NOT NULL AND ${table.evidenceJson} IS NOT NULL AND ${table.findingJson} IS NOT NULL AND ${table.findingDigest} IS NOT NULL)`),
    uniqueIndex("uq_research_sources_canonical").on(table.runId, table.dedupKey).where(sql`${table.duplicateOfSourceId} IS NULL`),
    index("idx_research_sources_claim").on(table.runId, table.status, table.ordinal),
  ],
);
