import { describe, expect, test } from "bun:test";
import type { BrowserContext } from "playwright-core";
import { PdfValidationError, validatePdf, type PdfValidationDeps } from "../src/services/export-pdf-validation";

const bytes = new TextEncoder().encode("%PDF-test");
type Phase = "load" | "metadata" | "page" | "operators" | "raster";
type Deferred<T> = { readonly promise: Promise<T>; readonly resolve: (value: T) => void; readonly reject: (error: unknown) => void };
function deferred<T>(): Deferred<T> { let resolve!: (value: T) => void; let reject!: (error: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
function turn(): Promise<void> { return new Promise((resolve) => setImmediate(resolve)); }

function controlled(phase: Phase, rejectDestroy = false, deadlineMs = 60_000) {
  const entered = deferred<void>(); const loadingStarted = deferred<void>(); const documentStarted = deferred<void>(); const loadingRelease = deferred<void>(); const documentRelease = deferred<void>(); const counts = { loading: 0, document: 0, page: 0 }; const controller = new AbortController();
  const page = { getViewport: () => ({ width: 200, height: 100 }), getOperatorList: () => { if (phase === "operators") { entered.resolve(); return new Promise<{ fnArray: unknown[] }>(() => {}); } return Promise.resolve({ fnArray: [1] }); }, cleanup: () => { counts.page += 1; }, render: () => ({}) };
  const document = { numPages: 1, getMetadata: () => { if (phase === "metadata") { entered.resolve(); return new Promise<{ info: unknown }>(() => {}); } return Promise.resolve({ info: { Title: "Deck" } }); }, getPage: () => { if (phase === "page") { entered.resolve(); return new Promise<typeof page>(() => {}); } return Promise.resolve(page); }, destroy: async () => { counts.document += 1; documentStarted.resolve(); await documentRelease.promise; if (rejectDestroy) throw new Error("document destroy failed"); } };
  const deps: PdfValidationDeps = { deadlineMs, load: () => { if (phase === "load") entered.resolve(); return { promise: phase === "load" ? new Promise<typeof document>(() => {}) : Promise.resolve(document), destroy: async () => { counts.loading += 1; loadingStarted.resolve(); await loadingRelease.promise; if (rejectDestroy) throw new Error("loading destroy failed"); } }; }, raster: (_page, signal) => { if (phase !== "raster") return Promise.resolve(rasterResult); entered.resolve(); return new Promise((_, reject) => signal.addEventListener("abort", () => reject(new Error("render cancelled")), { once: true })); } };
  const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck", signal: controller.signal }, deps); return { entered, loadingStarted, documentStarted, loadingRelease, documentRelease, counts, controller, operation };
}
const rasterResult = { raster_width: 400, raster_height: 200, statistics: { pixels: 80_000, visible_pixels: 80_000, painted_pixels: 1_000, differing_pixels: 1_000, color_count: 2, dominant_ratio: 0.9875, luminance_variance: 10, entropy: 0.2 }, content_bounds: { left: 10, top: 10, right: 20, bottom: 20 } };
async function expectAborted(operation: Promise<unknown>): Promise<void> { try { await operation; throw new TypeError("expected abort"); } catch (error) { expect(error).toBeInstanceOf(PdfValidationError); if (!(error instanceof PdfValidationError)) throw error; expect(error.code).toBe("raster_aborted"); } }
function pageRace(multiPage = false) {
  const requested = deferred<void>(); const rawPage = deferred<ReturnType<typeof makePage>>(); const loadingRelease = deferred<void>(); const documentRelease = deferred<void>(); const controller = new AbortController(); const cleanups = [0, 0]; const destroys = { loading: 0, document: 0 }; const make = (index: number) => makePage(() => { cleanups[index] = (cleanups[index] ?? 0) + 1; }); const first = make(0); const late = make(multiPage ? 1 : 0);
  const document = { numPages: multiPage ? 2 : 1, getMetadata: () => Promise.resolve({ info: { Title: "Deck" } }), getPage: (number: number) => { if (multiPage && number === 1) return Promise.resolve(first); requested.resolve(); return rawPage.promise; }, destroy: async () => { destroys.document += 1; await documentRelease.promise; } }; const deps: PdfValidationDeps = { deadlineMs: 60_000, load: () => ({ promise: Promise.resolve(document), destroy: async () => { destroys.loading += 1; await loadingRelease.promise; } }), raster: () => Promise.resolve(rasterResult) }; const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: multiPage ? 2 : 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck", signal: controller.signal }, deps); return { requested, rawPage, late, loadingRelease, documentRelease, controller, cleanups, destroys, operation };
}
function makePage(cleanup: () => void) { return { getViewport: () => ({ width: 200, height: 100 }), getOperatorList: () => Promise.resolve({ fnArray: [1] }), cleanup, render: () => ({}) }; }

describe("single PDF validation deadline", () => {
  test("stalled loading waits for its exact destroy promise before rejecting", async () => {
    const scope = controlled("load", false, 0); let settled = false; void scope.operation.finally(() => { settled = true; }).catch(() => {}); await scope.entered.promise; await scope.loadingStarted.promise; await turn(); expect(settled).toBe(false); expect(scope.counts.loading).toBe(1); scope.loadingRelease.resolve(); await expectAborted(scope.operation); expect(settled).toBe(true); expect(scope.counts.loading).toBe(1);
  });
  test("pre-aborted caller still destroys a loading resource acquired afterward", async () => {
    const release = deferred<void>(); const started = deferred<void>(); const controller = new AbortController(); controller.abort(); let destroys = 0; const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck", signal: controller.signal }, { deadlineMs: 60_000, load: () => ({ promise: new Promise(() => {}), destroy: async () => { destroys += 1; started.resolve(); await release.promise; } }), raster: () => Promise.resolve(rasterResult) }); let settled = false; void operation.finally(() => { settled = true; }).catch(() => {}); await started.promise; await turn(); expect(settled).toBe(false); release.resolve(); await expectAborted(operation); expect(destroys).toBe(1);
  });
  for (const phase of ["metadata", "page", "operators", "raster"] as const) test(`${phase} abort waits for both memoized destroy promises`, async () => {
    const scope = controlled(phase); let settled = false; void scope.operation.finally(() => { settled = true; }).catch(() => {}); await scope.entered.promise; scope.controller.abort(); await Promise.all([scope.loadingStarted.promise, scope.documentStarted.promise]); await turn(); expect(settled).toBe(false); scope.loadingRelease.resolve(); await turn(); expect(settled).toBe(false); scope.documentRelease.resolve(); await expectAborted(scope.operation); expect(settled).toBe(true); expect(scope.counts).toEqual({ loading: 1, document: 1, page: phase === "operators" || phase === "raster" ? 1 : 0 });
  });
  for (const order of ["abort_then_resolve", "resolve_then_abort"] as const) test(`${order} gives a late page exactly one cleanup owner`, async () => {
    const scope = pageRace(); let settled = false; void scope.operation.finally(() => { settled = true; }).catch(() => {}); await scope.requested.promise; if (order === "abort_then_resolve") { scope.controller.abort(); scope.rawPage.resolve(scope.late); } else { scope.rawPage.resolve(scope.late); scope.controller.abort(); } try { await turn(); expect(scope.cleanups[0]).toBe(1); expect(settled).toBe(false); expect(scope.destroys).toEqual({ loading: 1, document: 1 }); } finally { scope.loadingRelease.resolve(); scope.documentRelease.resolve(); } await expectAborted(scope.operation); expect(scope.cleanups[0]).toBe(1);
  });
  test("a late next page and an already-consumed prior page each clean exactly once", async () => {
    const scope = pageRace(true); let settled = false; void scope.operation.finally(() => { settled = true; }).catch(() => {}); await scope.requested.promise; expect(scope.cleanups[0]).toBe(1); scope.controller.abort(); scope.rawPage.resolve(scope.late); try { await turn(); expect(scope.cleanups).toEqual([1, 1]); expect(settled).toBe(false); } finally { scope.loadingRelease.resolve(); scope.documentRelease.resolve(); } await expectAborted(scope.operation); expect(scope.cleanups).toEqual([1, 1]);
  });
  test("a document resolving after abort enters memoized destruction before settlement", async () => {
    const rawDocument = deferred<{ numPages: number; getMetadata: () => Promise<{ info: unknown }>; getPage: () => Promise<ReturnType<typeof makePage>>; destroy: () => Promise<void> }>(); const loadingRelease = deferred<void>(); const documentRelease = deferred<void>(); const controller = new AbortController(); const destroys = { loading: 0, document: 0 }; const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck", signal: controller.signal }, { deadlineMs: 60_000, load: () => ({ promise: rawDocument.promise, destroy: async () => { destroys.loading += 1; await loadingRelease.promise; } }), raster: () => Promise.resolve(rasterResult) }); let settled = false; void operation.finally(() => { settled = true; }).catch(() => {}); controller.abort(); rawDocument.resolve({ numPages: 1, getMetadata: () => Promise.resolve({ info: { Title: "Deck" } }), getPage: () => Promise.resolve(makePage(() => {})), destroy: async () => { destroys.document += 1; await documentRelease.promise; } }); await turn(); expect(destroys).toEqual({ loading: 1, document: 1 }); expect(settled).toBe(false); loadingRelease.resolve(); await turn(); expect(settled).toBe(false); documentRelease.resolve(); await expectAborted(operation); expect(destroys).toEqual({ loading: 1, document: 1 });
  });
  test("raster cancellation settles before its transferred page is cleaned", async () => {
    const rasterEntered = deferred<void>(); const rasterRelease = deferred<void>(); const loadingRelease = deferred<void>(); const documentRelease = deferred<void>(); const controller = new AbortController(); let rasterSettled = false; let cleanupAfterRaster = false; let settled = false; const page = makePage(() => { cleanupAfterRaster = rasterSettled; }); const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck", signal: controller.signal }, { deadlineMs: 60_000, load: () => ({ promise: Promise.resolve({ numPages: 1, getMetadata: () => Promise.resolve({ info: { Title: "Deck" } }), getPage: () => Promise.resolve(page), destroy: async () => { await documentRelease.promise; } }), destroy: async () => { await loadingRelease.promise; } }), raster: (_page, signal) => { rasterEntered.resolve(); return new Promise((_, reject) => signal.addEventListener("abort", async () => { await rasterRelease.promise; rasterSettled = true; reject(new Error("cancelled")); }, { once: true })); } }); void operation.finally(() => { settled = true; }).catch(() => {}); await rasterEntered.promise; controller.abort(); await turn(); expect(cleanupAfterRaster).toBe(false); expect(settled).toBe(false); rasterRelease.resolve(); await turn(); expect(cleanupAfterRaster).toBe(true); expect(settled).toBe(false); loadingRelease.resolve(); documentRelease.resolve(); await expectAborted(operation);
  });
  test("destroy rejection is observed while raster_aborted remains primary", async () => {
    const scope = controlled("metadata", true); const unhandled: unknown[] = []; const observe = (error: unknown): void => { unhandled.push(error); }; process.on("unhandledRejection", observe);
    try { await scope.entered.promise; scope.controller.abort(); await Promise.all([scope.loadingStarted.promise, scope.documentStarted.promise]); scope.loadingRelease.resolve(); scope.documentRelease.resolve(); await expectAborted(scope.operation); await turn(); expect(unhandled).toEqual([]); expect(scope.counts).toEqual({ loading: 1, document: 1, page: 0 }); } finally { process.off("unhandledRejection", observe); }
  });
  test("success waits for each owned resource to finish destruction exactly once", async () => {
    const scope = controlled("metadata"); scope.entered.resolve(); const successDeps: PdfValidationDeps = { deadlineMs: 60_000, load: () => ({ promise: Promise.resolve({ numPages: 1, getMetadata: () => Promise.resolve({ info: { Title: "Deck" } }), getPage: () => Promise.resolve({ getViewport: () => ({ width: 200, height: 100 }), getOperatorList: () => Promise.resolve({ fnArray: [1] }), cleanup: () => { scope.counts.page += 1; }, render: () => ({}) }), destroy: async () => { scope.counts.document += 1; scope.documentStarted.resolve(); await scope.documentRelease.promise; } }), destroy: async () => { scope.counts.loading += 1; scope.loadingStarted.resolve(); await scope.loadingRelease.promise; } }), raster: () => Promise.resolve(rasterResult) };
    let settled = false; const operation = validatePdf({ bytes, context: {} as BrowserContext, expectedPages: 1, expectedWidthPoints: 200, expectedHeightPoints: 100, expectedTitle: "Deck" }, successDeps); void operation.finally(() => { settled = true; }); await Promise.all([scope.loadingStarted.promise, scope.documentStarted.promise]); expect(settled).toBe(false); scope.documentRelease.resolve(); await turn(); expect(settled).toBe(false); scope.loadingRelease.resolve(); await expect(operation).resolves.toMatchObject({ pages: 1 }); expect(scope.counts).toEqual({ loading: 1, document: 1, page: 1 });
  });
});
