#!/bin/bash
# Sourced by task-8-export-http.sh after baseline exports are validated.

fault_api() { local method="$1" route="$2" payload="$3" output="$4" barrier="${5:-}"; local headers=(-H "Origin: $ORIGIN" -H "x-burnguard-capability: $CAP"); [ -z "$barrier" ] || headers+=(-H "x-bg-export-qa-barrier: $barrier"); [ -z "$payload" ] || headers+=(-H 'content-type: application/json' --data-binary "@$payload"); curl -sS --connect-timeout 5 --max-time 300 -b "$COOKIE" "${headers[@]}" -X "$method" -o "$output" -w '%{http_code}' "$BASE$route"; }
arm_barrier() { local token="$1" phase="$2" behavior="$3"; jq -n --arg token "$token" --arg phase "$phase" --arg behavior "$behavior" '{token:$token,phase:$phase,behavior:$behavior}' >"$E/barrier-$token.payload.json"; [ "$(fault_api POST /api/exports/qa/barriers "$E/barrier-$token.payload.json" "$E/barrier-$token.arm.json")" = 201 ]; }
wait_barrier() { local token="$1" output="$2"; curl -sS --connect-timeout 5 --max-time 300 -b "$COOKIE" -H "Origin: $ORIGIN" -H "x-burnguard-capability: $CAP" "$BASE/api/exports/qa/barriers/$token/wait" >"$output" & BARRIER_PID=$!; }
await_barrier() { wait "$BARRIER_PID"; BARRIER_PID=""; BARRIER_ATTEMPT="$(jq -er '.data.attempt_id' "$1")"; }
arm_event() { local regex="$1" output="$2" ready="$E/fault-event-ready.fifo" after diagnostics; after="$(awk '/^id:/{value=$2}END{print value+0}' "$SSE")"; EVENT_RESULT="$output.result"; diagnostics="$output.observer.jsonl"; rm -f "$EVENT_RESULT" "$ready" "$diagnostics"; mkfifo "$ready"; bun "$REPO_ROOT/scripts/qa/task-8-sse-wait.ts" "$BASE/api/sessions/$SESSION_ID/stream?after_sequence=$after" "$regex" "$ready" "$EVENT_RESULT" "$CAP" "$ORIGIN" "$diagnostics" & ARMED_PID=$!; IFS= read -r -t 10 armed <"$ready"; [ "$armed" = ready ]; rm -f "$ready"; }
await_event() { local output="$1" event; if ! wait "$ARMED_PID"; then ARMED_PID=""; return 1; fi; ARMED_PID=""; event="$(cat "$EVENT_RESULT")"; [[ "$event" != __BG_SSE_WAITER_ERROR__:* ]]; printf '%s\n' "$event" >"$output"; rm -f "$EVENT_RESULT"; }
restart_sse() { : >"$SSE"; curl -sS --connect-timeout 5 --max-time 1800 -N -b "$COOKIE" -H "Origin: $ORIGIN" -H "x-burnguard-capability: $CAP" "$BASE/api/sessions/$SESSION_ID/stream?after_sequence=0" >"$SSE" & SSE_PID=$!; }
restart_backend() { stop_backend; start_backend; restart_sse; }
crash_backend() { stop_pid "$SSE_PID"; SSE_PID=""; local killed="$BG_PID"; kill -KILL "$killed" 2>/dev/null || true; wait "$killed" 2>/dev/null || true; BG_PID=""; printf '%s\n' "$killed"; }
db_tool() { local command="$1"; shift; HOME="$QA_HOME" bun "$REPO_ROOT/scripts/qa/task-8-export-db.ts" "$command" "$QA_HOME/.burnguard/burnguard.db" "$QA_HOME/.burnguard/cache/exports" "$@"; }
restore_baseline() { rm -f "$QA_HOME/.burnguard/burnguard.db"{,-wal,-shm}; cp "$QA_TMP/fault-baseline.db" "$QA_HOME/.burnguard/burnguard.db"; rm -rf "$QA_HOME/.burnguard/cache/exports"; cp -R "$QA_TMP/fault-baseline-exports" "$QA_HOME/.burnguard/cache/exports"; }

run_export_fault_matrix() {
  local token status job attempt hit stable_after dbroot="$QA_HOME/.burnguard/burnguard.db" exportroot="$QA_HOME/.burnguard/cache/exports"
  token="cancel_partial_$$"; arm_barrier "$token" after_partial_render pause; wait_barrier "$token" "$E/cancel-barrier-hit.json"
  jq -n '{format:"png",options:{png_width:640,png_height:360,png_dpr:1}}' >"$E/cancel-create.payload.json"; [ "$(fault_api POST "/api/projects/$PROJECT_ID/exports" "$E/cancel-create.payload.json" "$E/cancel-create.response.json" "$token")" = 202 ]; job="$(jq -er '.data.id' "$E/cancel-create.response.json")"; attempt="$(jq -er '.data.latest_attempt.id' "$E/cancel-create.response.json")"; await_barrier "$E/cancel-barrier-hit.json"; hit="$BARRIER_ATTEMPT"; [ "$hit" = "$attempt" ]
  arm_event "\"attemptId\":\"$attempt\".*\"status\":\"cancelled\"" "$E/cancel-event.jsonl"; [ "$(fault_api POST "/api/exports/$job/cancel" '' "$E/cancel.response.json")" = 202 ]; await_event "$E/cancel-event.jsonl"
  fault_api GET "/api/exports/$job" '' "$E/cancel-job.json" >"$E/cancel-job.status"; fault_api GET "/api/exports/$job/download" '' "$E/cancel-download.json" >"$E/cancel-download.status"
  [ ! -e "$exportroot/.staging/$attempt" ] && [ ! -e "$exportroot/attempts/$attempt" ]; jq -e '.data.latest_attempt.status=="cancelled" and .data.latest_attempt.stop_reason=="user_cancelled" and .data.status!="succeeded"' "$E/cancel-job.json" >/dev/null; [ "$(cat "$E/cancel-download.status")" = 409 ]
  curl -sS --connect-timeout 5 --max-time 20 -D "$E/stable-after-cancel.headers" -o /dev/null -b "$COOKIE" -H "Origin: $ORIGIN" -H "x-burnguard-capability: $CAP" "$BASE/api/projects/$PROJECT_ID/fs/$ENTRYPOINT"; stable_after="$(awk 'tolower($1)=="x-burnguard-artifact-digest:"{gsub("\r","");print $2}' "$E/stable-after-cancel.headers")"; [ "$stable_after" = "$DIGEST" ]

  token="retry_failure_$$"; arm_barrier "$token" after_partial_render fail; wait_barrier "$token" "$E/retry-failure-hit.json"; arm_event '"status":"failed"' "$E/retry-parent-event.jsonl"
  jq -n '{format:"png",options:{png_width:777,png_height:555,png_dpr:2}}' >"$E/retry-create.payload.json"; [ "$(fault_api POST "/api/projects/$PROJECT_ID/exports" "$E/retry-create.payload.json" "$E/retry-create.response.json" "$token")" = 202 ]; job="$(jq -er '.data.id' "$E/retry-create.response.json")"; attempt="$(jq -er '.data.latest_attempt.id' "$E/retry-create.response.json")"; await_barrier "$E/retry-failure-hit.json"; [ "$BARRIER_ATTEMPT" = "$attempt" ]; await_event "$E/retry-parent-event.jsonl"
  fault_api GET "/api/exports/$job" '' "$E/retry-parent-job.json" >"$E/retry-parent.status"; jq -e --arg parent "$attempt" '.data.latest_attempt.id==$parent and .data.latest_attempt.status=="failed"' "$E/retry-parent-job.json" >/dev/null
  jq -n --argjson revision "$REV" --arg digest "$DIGEST" '{project_revision:$revision,project_digest:$digest}' >"$E/retry.payload.json"; arm_event '"status":"validated"' "$E/retry-child-event.jsonl"
  fault_api POST "/api/exports/$job/retry" "$E/retry.payload.json" "$E/retry-a.json" >"$E/retry-a.status" & local retry_a=$!; fault_api POST "/api/exports/$job/retry" "$E/retry.payload.json" "$E/retry-b.json" >"$E/retry-b.status" & local retry_b=$!; wait "$retry_a"; wait "$retry_b"
  jq -n --arg a "$(cat "$E/retry-a.status")" --arg b "$(cat "$E/retry-b.status")" '{statuses:[$a,$b]}' >"$E/retry-race.json"; jq -e '.statuses|sort==["202","409"]' "$E/retry-race.json" >/dev/null; await_event "$E/retry-child-event.jsonl"
  fault_api GET "/api/exports/$job" '' "$E/retry-child-job.json" >"$E/retry-child.status"; fault_api GET "/api/exports/$job/download" '' "$E/retry-output.png" >"$E/retry-download.status"; jq -e --arg parent "$attempt" '.data.latest_attempt.status=="validated" and .data.latest_attempt.parent_attempt_id==$parent and .data.options=={png_width:777,png_height:555,png_dpr:2}' "$E/retry-child-job.json" >/dev/null; [ "$(cat "$E/retry-download.status")" = 200 ]
  db_tool inspect "$job" >"$E/retry-authority.json"; jq -e 'length==2 and .[0].canonical_options_json==.[1].canonical_options_json and .[0].options_digest==.[1].options_digest and .[0].project_digest==.[1].project_digest' "$E/retry-authority.json" >/dev/null

  token="publish_crash_$$"; arm_barrier "$token" after_publish_before_db pause; wait_barrier "$token" "$E/publish-crash-hit.json"; jq -n '{format:"png",options:{png_width:800,png_height:450,png_dpr:1}}' >"$E/publish-crash.payload.json"; [ "$(fault_api POST "/api/projects/$PROJECT_ID/exports" "$E/publish-crash.payload.json" "$E/publish-crash.response.json" "$token")" = 202 ]; job="$(jq -er '.data.id' "$E/publish-crash.response.json")"; attempt="$(jq -er '.data.latest_attempt.id' "$E/publish-crash.response.json")"; await_barrier "$E/publish-crash-hit.json"; [ "$BARRIER_ATTEMPT" = "$attempt" ]; [ -d "$exportroot/attempts/$attempt" ]; db_tool inspect "$job" >"$E/publish-before-kill.json"; jq -e '.[0].status=="validating"' "$E/publish-before-kill.json" >/dev/null; crash_backend >"$E/publish-killed.pid"; start_backend; restart_sse
  fault_api GET "/api/exports/$job" '' "$E/publish-recovered-job.json" >"$E/publish-recovered.status"; fault_api GET "/api/exports/$job/download" '' "$E/publish-recovered.png" >"$E/publish-recovered-download.status"; jq -e '.data.status=="succeeded" and .data.latest_attempt.status=="validated"' "$E/publish-recovered-job.json" >/dev/null; [ "$(cat "$E/publish-recovered-download.status")" = 200 ]; [ "$(jq 'length' "$E/publish-before-kill.json")" = 1 ]

  stop_backend; rm -f "$QA_TMP/fault-baseline.db"; bun -e 'import {Database} from "bun:sqlite";const db=new Database(process.argv[1]);db.prepare("VACUUM INTO ?").run(process.argv[2]);db.close()' "$dbroot" "$QA_TMP/fault-baseline.db"; cp -R "$exportroot" "$QA_TMP/fault-baseline-exports"
  : >"$E/corruption-results.jsonl"; for mutation in row receipt validation project_id parent options_authority provenance png_option_mismatch pdf_cross_field output; do restore_baseline; local corrupt_job="$job"; if [ "$mutation" = pdf_cross_field ]; then corrupt_job="$(jq -er '.[]|select(.format=="pdf")|.id' "$E/export-authority.json")"; fi; db_tool inspect "$corrupt_job" >"$E/corrupt-$mutation-before.json"; local expected_output expected_receipt; expected_output="$(jq -er '.[0].output_digest' "$E/corrupt-$mutation-before.json")"; expected_receipt="$(jq -er '.[0].receipt_digest' "$E/corrupt-$mutation-before.json")"; db_tool mutate "$corrupt_job" "$mutation"; start_backend; fault_api GET "/api/exports/$corrupt_job" '' "$E/corrupt-$mutation-job.json" >"$E/corrupt-$mutation-job.status"; fault_api GET "/api/exports/$corrupt_job/download" '' "$E/corrupt-$mutation-download.json" >"$E/corrupt-$mutation-download.status"; jq -nc --arg mutation "$mutation" --arg status "$(cat "$E/corrupt-$mutation-download.status")" --arg expected_output "$expected_output" --arg expected_receipt "$expected_receipt" --argjson before "$(jq '.[0]' "$E/corrupt-$mutation-before.json")" --argjson job "$(jq '.data' "$E/corrupt-$mutation-job.json")" '{mutation:$mutation,http:$status,job:$job,no_forged_propagation:($mutation=="row" or ($job.id==$before.job_id and $job.project_id==$before.project_id and $job.format==$before.format and $job.options==($before.options_json|fromjson) and $job.latest_attempt.id==$before.id and $job.latest_attempt.parent_attempt_id==$before.parent_attempt_id and $job.latest_attempt.project_revision==$before.project_revision and $job.latest_attempt.project_digest==$before.project_digest and $job.latest_attempt.digests.options==$before.options_digest and $job.latest_attempt.digests.input_closure==$before.input_closure_digest and $job.latest_attempt.digests.design_system==$before.design_system_digest and $job.latest_attempt.digests.renderer==$before.renderer_digest and $job.latest_attempt.digests.capture==$before.capture_digest and $job.latest_attempt.digests.output==$expected_output and $job.latest_attempt.digests.receipt==$expected_receipt))}' >>"$E/corruption-results.jsonl"; jq -e '.data.status=="failed" and .data.latest_attempt.status=="corrupt" and .data.latest_attempt.stop_reason=="receipt_corrupt"' "$E/corrupt-$mutation-job.json" >/dev/null; if [ "$mutation" = pdf_cross_field ]; then jq -e --arg output "$expected_output" --arg receipt "$expected_receipt" '.data.latest_attempt.digests.output==$output and .data.latest_attempt.digests.receipt==$receipt' "$E/corrupt-$mutation-job.json" >/dev/null; fi; [ "$(cat "$E/corrupt-$mutation-download.status")" = 409 ]; stop_backend; done
  jq -s 'map(select(.mutation=="pdf_cross_field"))[0] | {mutation,http,typed_status:.job.latest_attempt.status,stop_reason:.job.latest_attempt.stop_reason,no_forged_propagation,rejected:(.http=="409" and .job.latest_attempt.status=="corrupt" and .job.latest_attempt.stop_reason=="receipt_corrupt" and .no_forged_propagation)}' "$E/corruption-results.jsonl" >"$E/cross-field-forged-evidence-rejection.json"; jq -e '.rejected' "$E/cross-field-forged-evidence-rejection.json" >/dev/null
  restore_baseline; db_tool seed-states "$job"; start_backend; restart_sse; for state in pending running validating retrying recovering; do fault_api GET "/api/exports/qa-state-$state" '' "$E/nonterminal-$state.json" >"$E/nonterminal-$state.status"; done; db_tool inspect >"$E/nonterminal-first-restart.json"; restart_backend; db_tool inspect >"$E/nonterminal-second-restart.json"; diff -u "$E/nonterminal-first-restart.json" "$E/nonterminal-second-restart.json" >"$E/nonterminal-idempotence.diff"; jq -e '.data.latest_attempt.status=="failed"' "$E/nonterminal-pending.json" >/dev/null; jq -e '.data.latest_attempt.status=="corrupt"' "$E/nonterminal-running.json" >/dev/null; jq -e '.data.latest_attempt.status=="validated"' "$E/nonterminal-validating.json" >/dev/null; jq -e '.data.latest_attempt.status=="failed"' "$E/nonterminal-retrying.json" >/dev/null; jq -e '.data.latest_attempt.status=="validated"' "$E/nonterminal-recovering.json" >/dev/null

  token="gc_before_$$"; arm_barrier "$token" gc_after_tombstone_before_unlink pause; wait_barrier "$token" "$E/gc-before-hit.json"; jq -n --argjson now "$(date +%s000)" '{now:$now,attempt_id:"qa-state-validating-attempt"}' >"$E/gc-before.payload.json"; fault_api POST /api/exports/qa/gc "$E/gc-before.payload.json" "$E/gc-before.response.json" "$token" >"$E/gc-before.status" & local gc_pid=$!; await_barrier "$E/gc-before-hit.json"; [ "$BARRIER_ATTEMPT" = qa-state-validating-attempt ]; [ -d "$exportroot/attempts/qa-state-validating-attempt" ]; crash_backend >"$E/gc-before-killed.pid"; start_backend; restart_sse; wait "$gc_pid" 2>/dev/null || true; [ ! -e "$exportroot/attempts/qa-state-validating-attempt" ]
  token="gc_after_$$"; arm_barrier "$token" gc_after_unlink pause; wait_barrier "$token" "$E/gc-after-hit.json"; jq -n --argjson now "$(date +%s000)" '{now:$now,attempt_id:"qa-state-recovering-attempt"}' >"$E/gc-after.payload.json"; fault_api POST /api/exports/qa/gc "$E/gc-after.payload.json" "$E/gc-after.response.json" "$token" >"$E/gc-after.status" & gc_pid=$!; await_barrier "$E/gc-after-hit.json"; [ "$BARRIER_ATTEMPT" = qa-state-recovering-attempt ]; [ ! -e "$exportroot/attempts/qa-state-recovering-attempt" ]; crash_backend >"$E/gc-after-killed.pid"; start_backend; restart_sse; wait "$gc_pid" 2>/dev/null || true; db_tool inspect >"$E/gc-authority.json"

  for format in html_zip pdf png; do local original; original="$(jq -er --arg format "$format" '.[]|select(.format==$format)|.id' "$E/export-authority.json")"; fault_api GET "/api/exports/$original/download" '' "$E/reopened-$format" >"$E/reopened-$format.status"; [ "$(cat "$E/reopened-$format.status")" = 200 ]; done
  uv run --with pymupdf --with pillow python - "$E" <<'PY' >"$E/reopened-validation.json"
import json,pathlib,sys,zipfile,pymupdf
from PIL import Image
r=pathlib.Path(sys.argv[1]); z=zipfile.ZipFile(r/'reopened-html_zip'); p=pymupdf.open(r/'reopened-pdf'); i=Image.open(r/'reopened-png'); print(json.dumps({'zip_entries':len(z.namelist()),'pdf_pages':len(p),'png_size':i.size}))
PY
  jq -e '.zip_entries>1 and .pdf_pages>0 and .png_size==[1280,720]' "$E/reopened-validation.json" >/dev/null; if jq -e 'false' >/dev/null; then return 1; else jq -n '{false_proof_rejected:true}' >"$E/false-proof-self-test.json"; fi
  jq -n --argjson cancel "$(jq '.data' "$E/cancel-job.json")" --argjson retry "$(jq '.data' "$E/retry-child-job.json")" --argjson race "$(cat "$E/retry-race.json")" --argjson crash "$(jq '.data' "$E/publish-recovered-job.json")" --argjson corrupt "$(jq -s . "$E/corruption-results.jsonl")" --argjson gc "$(cat "$E/gc-authority.json")" --argjson states "$(jq -s '[.[].data.latest_attempt.status]' "$E"/nonterminal-{pending,running,validating,retrying,recovering}.json)" --argjson reopened "$(cat "$E/reopened-validation.json")" --argjson idem "$(stat -f %z "$E/nonterminal-idempotence.diff")" '{forged_pdf_cross_field:($corrupt|any(.mutation=="pdf_cross_field" and .http=="409" and .job.latest_attempt.status=="corrupt" and .no_forged_propagation)),cancel:($cancel.latest_attempt.status=="cancelled" and $cancel.latest_attempt.stop_reason=="user_cancelled"),retry:($retry.latest_attempt.status=="validated" and $retry.latest_attempt.parent_attempt_id!=null and ($race.statuses|sort)==["202","409"]),publish_crash:($crash.status=="succeeded" and $crash.latest_attempt.status=="validated"),corruption:($corrupt|all(.http=="409" and .job.status=="failed" and .job.latest_attempt.status=="corrupt" and .no_forged_propagation)),nonterminal_restart:($idem==0 and $states==["failed","corrupt","validated","failed","validated"]),gc:([$gc[]|select(.job_id=="qa-state-validating" or .job_id=="qa-state-recovering")]|length==2 and all(.status=="expired" and (.retention_json|fromjson|.output_available==false))),reopened:($reopened.zip_entries>1 and $reopened.pdf_pages>0 and $reopened.png_size==[1280,720])}' >"$E/fault-matrix-proof.json"; jq -e '[.[]]|all' "$E/fault-matrix-proof.json" >/dev/null
  jq --slurpfile fault "$E/fault-matrix-proof.json" '. + $fault[0]' "$E/qa-proofs.json" >"$E/qa-proofs.tmp"; mv "$E/qa-proofs.tmp" "$E/qa-proofs.json"
}
